In [22]:
import os
import pandas as pd
from PIL import Image
import glob

# Define the directories containing the data
data_dir = '../HPI_Bilder_input_07/'
csv_dir = '../csv/CSV_Input_07'

# Initialize lists to store data
csv_data = []
images = []

# Use glob to list all CSV files in the csv directory
csv_files = glob.glob(os.path.join(csv_dir, '*.csv'))

# Iterate over the CSV files and load each one individually
for csv_file in csv_files:
    df = pd.read_csv(csv_file)
    csv_data.append(df)
    print(f"Loaded CSV file: {csv_file}")
    print(df.head())

# Use glob to list all files in the data directory and subdirectories
files = glob.glob(os.path.join(data_dir, '**'), recursive=True)

# Iterate over the files
for file_path in files:
    # Check if the file is a JPEG image
    if file_path.endswith('.jpeg'):
        img = Image.open(file_path)
        images.append(img)

# Display the number of images loaded
print(f"Number of images loaded: {len(images)}")

Loaded CSV file: ../csv/CSV_Input_07/Mengen Rückläufer (CSV).csv
   Bon_ID  Artikelnr  Menge_Rucklaufer  Prozent_Rucklaufer
0  480654   91862294                58               48.33
1  480654   91511750                12               30.00
2  480654   91511769                14               35.00
3  480654   91551949                26               52.00
4  480654   91533800                50               54.95
Loaded CSV file: ../csv/CSV_Input_07/Bon Nährwerte (CSV).csv
   Bon_ID                                            Gericht    Portionsgröße  \
0  480654  Hähnchenbrustfilet mit Erbsen und Möhren, Kart...  Normale Portion
1  480656  Hähnchen mit Kartoffeln , Erbsen Möhre und Bra...  Normale Portion
2  480657  Rostbratwurst mit Sauerkraut und Kartoffeln an...  Normale Portion
3  480658  Rostbratwurst mit Rotkohl , Kartoffelpüree , B...  Normale Portion
4  480659  Schweineschnitzel nach Jägerart mit Pilz-Rahms...  Normale Portion

   Gewicht_vorher kcal_vorher  kj_vorher Fett_vorher ges_Fettsäuren_vorher  \
0             341     315,250  1.323,220      10,293                 1,305
1             336     234,940    983,980       4,603                 0,725
2             325     326,570  1.363,620      19,630                 6,490
3             300     360,980  1.512,760      21,220                 6,540
4             365     307,590  1.279,400       9,260                 3,510

  Kohlenhydrate_vorher Zucker_vorher  ... Salz_vorher Gewicht_nachher  \
0               28,830         7,477  ...       3,404             197
1               25,385         8,252  ...       3,824             166
2               23,745         8,215  ...       5,430             195
3               28,000         8,570  ...       4,830             214
4               33,125         8,755  ...       3,830             237

   kcal_nachher kj_nachher Fett_nachher ges_fettsäuren_nachher  \
0       182,124    764,441        5,946                  0,754
1       116,072    486,133        2,274                  0,358
2       195,942    818,172       11,778                  3,894
3       257,499  1.079,102       15,137                  4,665
4       199,723    830,734        6,013                  2,279

  Kohlenhydrate_nachher Zucker_nachher Eiweiß_nachher Salz_nachher
0                16,655          4,320         14,204        1,967
1                12,541          4,077         10,356        1,889
2                14,247          4,929          7,113        3,258
3                19,973          6,113          8,503        3,445
4                21,509          5,685         13,327        2,487

[5 rows x 21 columns]
Loaded CSV file: ../csv/CSV_Input_07/Bon Zutaten (CSV).csv
   Bon_ID  Artikelnummer          Artikel Stückartikel  Anzahl_Kellen  \
0  480654       91862294  Kartoffelpüree             N              2
1  480654       91511750           Erbsen            N              1
2  480654       91511769            Möhre            N              1
3  480654       91551949        Bratenjus            N              1
4  480654       91533800        Hähnchen             J              1

  Gewicht_Kelle Gewicht_Teller kcal_Teller kj_Teller Fett_Teller  \
0          60,0          120,0     129,960   544,440       5,640
1          40,0           40,0      36,400   151,600       1,160
2          40,0           40,0      18,800    78,800       1,000
3          50,0           50,0      42,000   177,500       0,350
4          91,0           91,0      90,090   380,380       2,093

  ges_Fettsäuren_Teller Kohlenhydrate_Teller Zucker_Teller Eiweiß_Teller  \
0                 0,600               16,440         0,480         2,040
1                 0,120                3,480         1,200         2,000
2                 0,080                2,240         2,160         0,240
3                 0,050                5,500         3,400         4,000
4                 0,455                1,820         0,637        16,107

  Salz_Teller
0       0,960
1       0,040
2       0,280
3       0,700
4       1,274
Number of images loaded: 1

In [23]:
csv_data[0]

    Bon_ID  Artikelnr  Menge_Rucklaufer  Prozent_Rucklaufer
0   480654   91862294                58               48.33
1   480654   91511750                12               30.00
2   480654   91511769                14               35.00
3   480654   91551949                26               52.00
4   480654   91533800                50               54.95
5   480656   91511793                62               65.26
6   480656   91511750                24               60.00
7   480656   91511769                38               95.00
8   480656   91511823                18               25.71
9   480656   91533800                42               46.15
10  480657   91511793                42               44.21
11  480657   90284505                42               42.00
12  480657   91511823                26               37.14
13  480657   91613413                26               43.33
14  480658   91862294                32               53.33
15  480658   91366696                36               72.00
16  480658   91511823                12               34.29
17  480658   91613413                14               23.33
18  480659   91511793                30               31.57
19  480659   91511750                12               30.00
20  480659   91511769                16               40.00
21  480659   91613421                48               60.00
22  480659   91428764                 2               20.00
23  480659   91511823                16               22.86
24  480659   91388363                14               46.66
25  480660   91511777                26               40.00
26  480660   91434357                34               34.00
27  480660   91511831                26               52.00

In [24]:
csv_data[1]

,Bon_ID,Gericht,Portionsgröße,Gewicht_vorher,kcal_vorher,kj_vorher,Fett_vorher,ges_Fettsäuren_vorher,Kohlenhydrate_vorher,Zucker_vorher,...,Salz_vorher,Gewicht_nachher,kcal_nachher,kj_nachher,Fett_nachher,ges_fettsäuren_nachher,Kohlenhydrate_nachher,Zucker_nachher,Eiweiß_nachher,Salz_nachher
0,480654,"Hähnchenbrustfilet mit Erbsen und Möhren, Kart...",Normale Portion,341,"315,250","1.323,220","10,293","1,305","28,830","7,477",...,"3,404",197,"182,124","764,441","5,946","0,754","16,655","4,320","14,204","1,967"
1,480656,"Hähnchen mit Kartoffeln , Erbsen Möhre und Bra...",Normale Portion,336,"234,940","983,980","4,603","0,725","25,385","8,252",...,"3,824",166,"116,072","486,133","2,274","0,358","12,541","4,077","10,356","1,889"
2,480657,Rostbratwurst mit Sauerkraut und Kartoffeln an...,Normale Portion,325,"326,570","1.363,620","19,630","6,490","23,745","8,215",...,"5,430",195,"195,942","818,172","11,778","3,894","14,247","4,929","7,113","3,258"
3,480658,"Rostbratwurst mit Rotkohl , Kartoffelpüree , B...",Normale Portion,300,"360,980","1.512,760","21,220","6,540","28,000","8,570",...,"4,830",214,"257,499","1.079,102","15,137","4,665","19,973","6,113","8,503","3,445"
4,480659,Schweineschnitzel nach Jägerart mit Pilz-Rahms...,Normale Portion,365,"307,590","1.279,400","9,260","3,510","33,125","8,755",...,"3,830",237,"199,723","830,734","6,013","2,279","21,509","5,685","13,327","2,487"
5,480660,"Paniertes Fischfilet mit Blumenkohl , Reis , H...",Normale Portion,315,"307,850","1.294,350","11,110","3,465","35,090","4,415",...,"2,190",185,"180,801","760,174","6,525","2,035","20,608","2,593","9,133","1,286"

In [25]:
csv_data[2]

,Bon_ID,Artikelnummer,Artikel,Stückartikel,Anzahl_Kellen,Gewicht_Kelle,Gewicht_Teller,kcal_Teller,kj_Teller,Fett_Teller,ges_Fettsäuren_Teller,Kohlenhydrate_Teller,Zucker_Teller,Eiweiß_Teller,Salz_Teller
0,480654,91862294,Kartoffelpüree,N,2,"60,0","120,0","129,960","544,440","5,640","0,600","16,440","0,480","2,040","0,960"
1,480654,91511750,Erbsen,N,1,"40,0","40,0","36,400","151,600","1,160","0,120","3,480","1,200","2,000","0,040"
2,480654,91511769,Möhre,N,1,"40,0","40,0","18,800","78,800","1,000","0,080","2,240","2,160","0,240","0,280"
3,480654,91551949,Bratenjus,N,1,"50,0","50,0","42,000","177,500","0,350","0,050","5,500","3,400","4,000","0,700"
4,480654,91533800,Hähnchen,J,1,"91,0","91,0","90,090","380,380","2,093","0,455","1,820","0,637","16,107","1,274"
5,480656,91511793,Kartoffeln,N,1,"95,0","95,0","56,050","231,800","0,000","0,000","11,685","0,475","1,425","0,760"
6,480656,91511750,Erbsen,N,1,"40,0","40,0","36,400","151,600","1,160","0,120","3,480","1,200","2,000","0,040"
7,480656,91511769,Möhre,N,1,"40,0","40,0","18,800","78,800","1,000","0,080","2,240","2,160","0,240","0,280"
8,480656,91511823,Braune Sauce,N,2,"35,0","70,0","82,600","344,400","4,830","0,350","7,630","5,880","1,260","1,680"
9,480656,91533800,Hähnchen,J,1,"91,0","91,0","90,090","380,380","2,093","0,455","1,820","0,637","16,107","1,274"
10,480657,91511793,Kartoffeln,N,1,"95,0","95,0","56,050","231,800","0,000","0,000","11,685","0,475","1,425","0,760"
11,480657,90284505,Sauerkraut,N,2,"50,0","100,0","64,000","267,000","4,100","0,600","5,000","3,300","1,200","1,400"
12,480657,91511823,Braune Sauce,N,2,"35,0","70,0","82,600","344,400","4,830","0,350","7,630","5,880","1,260","1,680"
13,480657,91613413,Rostbratwurst,J,1,"60,0","60,0","172,920","723,420","15,180","5,820","0,900","0,660","8,040","1,800"
14,480658,91862294,Kartoffelpüree,N,2,"60,0","120,0","129,960","544,440","5,640","0,600","16,440","0,480","2,040","0,960"
15,480658,91366696,Rotkohl,N,1,"50,0","50,0","24,500","103,500","0,050","0,050","4,500","3,650","0,650","0,600"
16,480658,91511823,Braune Sauce,N,2,"35,0","70,0","82,600","344,400","4,830","0,350","7,630","5,880","1,260","1,680"
17,480658,91613413,Rostbratwurst,J,1,"60,0","60,0","172,920","723,420","15,180","5,820","0,900","0,660","8,040","1,800"
18,480659,91511793,Kartoffeln,N,1,"95,0","95,0","56,050","231,800","0,000","0,000","11,685","0,475","1,425","0,760"
19,480659,91511750,Erbsen,N,1,"40,0","40,0","36,400","151,600","1,160","0,120","3,480","1,200","2,000","0,040"
20,480659,91511769,Möhre,N,1,"40,0","40,0","18,800","78,800","1,000","0,080","2,240","2,160","0,240","0,280"
21,480659,91613421,Schnitzel,J,1,"80,0","80,0","127,040","529,200","3,600","1,200","8,720","0,720","14,880","1,120"
22,480659,91388363,Pilze,N,1,"30,0","30,0","9,150","38,700","0,060","0,000","0,840","0,120","1,260","0,300"
23,480659,91428764,Sahne,N,1,"10,0","10,0","29,400","121,400","3,000","2,010","0,360","0,360","0,250","0,010"
24,480659,91511823,Braune Sauce,N,2,"35,0","70,0","82,600","344,400","4,830","0,350","7,630","5,880","1,260","1,680"
25,480660,91511777,Reis,N,1,"65,0","65,0","64,350","272,350","0,260","0,065","14,040","0,065","1,300","0,390"
26,480660,91434357,Blumenkohl,N,2,"50,0","100,0","31,000","131,000","0,900","0,200","2,100","1,800","2,900","0,600"
27,480660,93709884,Paniertes Fischfilet,J,1,"100,0","100,0","181,000","760,000","7,500","1,600","17,000","2,000","11,000","1,000"
28,480660,91511831,Helle Sauce,N,1,"50,0","50,0","85,000","350,000","8,350","2,850","2,050","0,400","0,250","0,200"

In [26]:
df1 = csv_data[2]
df2 = csv_data[0]
# df3 = df1.merge(df2, how='left', left_on=['Bon_ID', 'Artikelnummer'], right_on=['Bon_ID', 'Artikelnr'])
df3 = df1.copy()

# Convert Menge_Rucklaufer and Prozent_Rucklaufer to float
df2['Menge_Rucklaufer'] = df2['Menge_Rucklaufer'].apply(lambda x: float(str(x).replace(',', '.')))
df2['Prozent_Rucklaufer'] = df2['Prozent_Rucklaufer'].apply(lambda x: float(str(x).replace(',', '.')))

# Add the new columns to df3
df3['Menge_Rucklaufer'] = 0
df3['Prozent_Rucklaufer'] = 0
df3['Menge_Rucklaufer'] = df3['Menge_Rucklaufer'].astype(float)
df3['Prozent_Rucklaufer'] = df3['Prozent_Rucklaufer'].astype(float)
# First, add the values for non-NaN Artikelnr
for _, row in df2.iterrows():
    bon_id = int(row['Bon_ID'])
    artikelnr = row['Artikelnr']
    menge_ruecklaeufer = row['Menge_Rucklaufer']
    prozent_ruecklaeufer = row['Prozent_Rucklaufer']
    
    if pd.notna(artikelnr):
        # If Artikelnr is not NaN, add the values to the corresponding rows in df1
        df3.loc[(df3['Bon_ID'] == bon_id) & (df3['Artikelnummer'] == artikelnr), 'Menge_Rucklaufer'] += menge_ruecklaeufer
        df3.loc[(df3['Bon_ID'] == bon_id) & (df3['Artikelnummer'] == artikelnr), 'Prozent_Rucklaufer'] += prozent_ruecklaeufer

# Then, distribute the values for NaN Artikelnr
for _, row in df2.iterrows():
    bon_id = int(row['Bon_ID'])
    artikelnr = row['Artikelnr']
    menge_ruecklaeufer = row['Menge_Rucklaufer']
    prozent_ruecklaeufer = row['Prozent_Rucklaufer']
    
    if pd.isna(artikelnr):
        # If Artikelnr is NaN, distribute the values among the rest of the Artikelnr found in the Bon_ID
        df1_subset = df3[(df3['Bon_ID'] == bon_id) & (df3['Menge_Rucklaufer'] == 0) & (df3['Prozent_Rucklaufer'] == 0)]
        num_existing_artikelnr = len(df1_subset)
        if num_existing_artikelnr > 0:
            df3.loc[(df3['Bon_ID'] == bon_id) & (df3['Menge_Rucklaufer'] == 0), 'Menge_Rucklaufer'] += menge_ruecklaeufer / num_existing_artikelnr
            df3.loc[(df3['Bon_ID'] == bon_id) & (df3['Prozent_Rucklaufer'] == 0), 'Prozent_Rucklaufer'] += prozent_ruecklaeufer / num_existing_artikelnr

# Display the updated DataFrame
print(df3.head())

   Bon_ID  Artikelnummer          Artikel Stückartikel  Anzahl_Kellen  \
0  480654       91862294  Kartoffelpüree             N              2
1  480654       91511750           Erbsen            N              1
2  480654       91511769            Möhre            N              1
3  480654       91551949        Bratenjus            N              1
4  480654       91533800        Hähnchen             J              1

  Gewicht_Kelle Gewicht_Teller kcal_Teller kj_Teller Fett_Teller  \
0          60,0          120,0     129,960   544,440       5,640
1          40,0           40,0      36,400   151,600       1,160
2          40,0           40,0      18,800    78,800       1,000
3          50,0           50,0      42,000   177,500       0,350
4          91,0           91,0      90,090   380,380       2,093

  ges_Fettsäuren_Teller Kohlenhydrate_Teller Zucker_Teller Eiweiß_Teller  \
0                 0,600               16,440         0,480         2,040
1                 0,120                3,480         1,200         2,000
2                 0,080                2,240         2,160         0,240
3                 0,050                5,500         3,400         4,000
4                 0,455                1,820         0,637        16,107

  Salz_Teller  Menge_Rucklaufer  Prozent_Rucklaufer
0       0,960              58.0               48.33
1       0,040              12.0               30.00
2       0,280              14.0               35.00
3       0,700              26.0               52.00
4       1,274              50.0               54.95

In [27]:
df3.drop(df3[df3['Bon_ID'] == 463705].index, inplace=True)

In [28]:
df3.to_csv('merged_data.csv', index=False)

In [29]:
df3

,Bon_ID,Artikelnummer,Artikel,Stückartikel,Anzahl_Kellen,Gewicht_Kelle,Gewicht_Teller,kcal_Teller,kj_Teller,Fett_Teller,ges_Fettsäuren_Teller,Kohlenhydrate_Teller,Zucker_Teller,Eiweiß_Teller,Salz_Teller,Menge_Rucklaufer,Prozent_Rucklaufer
0,480654,91862294,Kartoffelpüree,N,2,"60,0","120,0","129,960","544,440","5,640","0,600","16,440","0,480","2,040","0,960",58.0,48.33
1,480654,91511750,Erbsen,N,1,"40,0","40,0","36,400","151,600","1,160","0,120","3,480","1,200","2,000","0,040",12.0,30.00
2,480654,91511769,Möhre,N,1,"40,0","40,0","18,800","78,800","1,000","0,080","2,240","2,160","0,240","0,280",14.0,35.00
3,480654,91551949,Bratenjus,N,1,"50,0","50,0","42,000","177,500","0,350","0,050","5,500","3,400","4,000","0,700",26.0,52.00
4,480654,91533800,Hähnchen,J,1,"91,0","91,0","90,090","380,380","2,093","0,455","1,820","0,637","16,107","1,274",50.0,54.95
5,480656,91511793,Kartoffeln,N,1,"95,0","95,0","56,050","231,800","0,000","0,000","11,685","0,475","1,425","0,760",62.0,65.26
6,480656,91511750,Erbsen,N,1,"40,0","40,0","36,400","151,600","1,160","0,120","3,480","1,200","2,000","0,040",24.0,60.00
7,480656,91511769,Möhre,N,1,"40,0","40,0","18,800","78,800","1,000","0,080","2,240","2,160","0,240","0,280",38.0,95.00
8,480656,91511823,Braune Sauce,N,2,"35,0","70,0","82,600","344,400","4,830","0,350","7,630","5,880","1,260","1,680",18.0,25.71
9,480656,91533800,Hähnchen,J,1,"91,0","91,0","90,090","380,380","2,093","0,455","1,820","0,637","16,107","1,274",42.0,46.15
10,480657,91511793,Kartoffeln,N,1,"95,0","95,0","56,050","231,800","0,000","0,000","11,685","0,475","1,425","0,760",42.0,44.21
11,480657,90284505,Sauerkraut,N,2,"50,0","100,0","64,000","267,000","4,100","0,600","5,000","3,300","1,200","1,400",42.0,42.00
12,480657,91511823,Braune Sauce,N,2,"35,0","70,0","82,600","344,400","4,830","0,350","7,630","5,880","1,260","1,680",26.0,37.14
13,480657,91613413,Rostbratwurst,J,1,"60,0","60,0","172,920","723,420","15,180","5,820","0,900","0,660","8,040","1,800",26.0,43.33
14,480658,91862294,Kartoffelpüree,N,2,"60,0","120,0","129,960","544,440","5,640","0,600","16,440","0,480","2,040","0,960",32.0,53.33
15,480658,91366696,Rotkohl,N,1,"50,0","50,0","24,500","103,500","0,050","0,050","4,500","3,650","0,650","0,600",36.0,72.00
16,480658,91511823,Braune Sauce,N,2,"35,0","70,0","82,600","344,400","4,830","0,350","7,630","5,880","1,260","1,680",12.0,34.29
17,480658,91613413,Rostbratwurst,J,1,"60,0","60,0","172,920","723,420","15,180","5,820","0,900","0,660","8,040","1,800",14.0,23.33
18,480659,91511793,Kartoffeln,N,1,"95,0","95,0","56,050","231,800","0,000","0,000","11,685","0,475","1,425","0,760",30.0,31.57
19,480659,91511750,Erbsen,N,1,"40,0","40,0","36,400","151,600","1,160","0,120","3,480","1,200","2,000","0,040",12.0,30.00
20,480659,91511769,Möhre,N,1,"40,0","40,0","18,800","78,800","1,000","0,080","2,240","2,160","0,240","0,280",16.0,40.00
21,480659,91613421,Schnitzel,J,1,"80,0","80,0","127,040","529,200","3,600","1,200","8,720","0,720","14,880","1,120",48.0,60.00
22,480659,91388363,Pilze,N,1,"30,0","30,0","9,150","38,700","0,060","0,000","0,840","0,120","1,260","0,300",14.0,46.66
23,480659,91428764,Sahne,N,1,"10,0","10,0","29,400","121,400","3,000","2,010","0,360","0,360","0,250","0,010",2.0,20.00
24,480659,91511823,Braune Sauce,N,2,"35,0","70,0","82,600","344,400","4,830","0,350","7,630","5,880","1,260","1,680",16.0,22.86
25,480660,91511777,Reis,N,1,"65,0","65,0","64,350","272,350","0,260","0,065","14,040","0,065","1,300","0,390",26.0,40.00
26,480660,91434357,Blumenkohl,N,2,"50,0","100,0","31,000","131,000","0,900","0,200","2,100","1,800","2,900","0,600",34.0,34.00
27,480660,93709884,Paniertes Fischfilet,J,1,"100,0","100,0","181,000","760,000","7,500","1,600","17,000","2,000","11,000","1,000",0.0,0.00
28,480660,91511831,Helle Sauce,N,1,"50,0","50,0","85,000","350,000","8,350","2,850","2,050","0,400","0,250","0,200",26.0,52.00