In [1]:
import os
import pandas as pd
from PIL import Image
import glob

# Define the directories containing the data
data_dir = '../images/'
csv_dir = '../csv/'

# Initialize lists to store data
csv_data = []
images = []

# Use glob to list all CSV files in the csv directory
csv_files = glob.glob(os.path.join(csv_dir, '*.csv'))

# Iterate over the CSV files and load each one individually
for csv_file in csv_files:
    df = pd.read_csv(csv_file)
    csv_data.append(df)
    print(f"Loaded CSV file: {csv_file}")
    print(df.head())

# Use glob to list all files in the data directory and subdirectories
files = glob.glob(os.path.join(data_dir, '**'), recursive=True)

# Iterate over the files
for file_path in files:
    # Check if the file is a JPEG image
    if file_path.endswith('.jpeg'):
        img = Image.open(file_path)
        images.append(img)

# Display the number of images loaded
print(f"Number of images loaded: {len(images)}")

Loaded CSV file: ../csv/Bon Nährwerte (CSV) - 2.csv
   Bon_ID                                            Gericht    Portionsgröße  \
0  463705  Rinderbraten mit Wirsing , Kartoffelpüree , Du...  Normale Portion
1  463706  Rinderbraten mit Wirsing , Kartoffelpüree , Du...  Normale Portion
2  463707  Schweinenackenbraten mit Rotkohl , Kartoffeln ...  Normale Portion
3  463711  Schweinenackenbraten , Rotkohl , Kartoffeln , ...  Normale Portion
4  463712        Pasta mit Pilzen und Gemüse an Tomatensauce  Normale Portion

   Gewicht_vorher kcal_vorher  kj_vorher Fett_vorher ges_Fettsäuren_vorher  \
0             340     302,160  1.262,940      11,160                 2,710
1             340     302,160  1.262,940      11,160                 2,710
2             295     299,850  1.254,800      14,000                 5,120
3             295     299,850  1.254,800      14,000                 5,120
4             340     341,500  1.433,300       7,630                 1,070

  Kohlenhydrate_vorher Zucker_vorher  ... Salz_vorher Gewicht_nachher  \
0               25,300         6,960  ...       2,870             630
1               25,300         6,960  ...       2,870             298
2               23,265         8,625  ...       2,530             247
3               23,265         8,625  ...       2,530             203
4               53,190         9,240  ...       1,650             266

   kcal_nachher kj_nachher Fett_nachher ges_fettsäuren_nachher  \
0       281,484  1.176,556       10,354                  2,556
1       261,078  1.091,247        9,593                  2,244
2       215,690    902,420        8,410                  3,026
3       190,930    799,500        8,398                  3,014
4       267,174  1.121,346        5,969                  0,837

  Kohlenhydrate_nachher Zucker_nachher Eiweiß_nachher Salz_nachher
0                23,314          6,636         21,038        2,678
1                22,871          6,292         18,151        2,510
2                21,711          7,923         11,617        2,092
3                16,695          6,887         10,981        1,692
4                41,613          7,229          9,435        1,291

[5 rows x 21 columns]
Loaded CSV file: ../csv/Bon Zutaten (CSV) - 2.csv
   Bon_ID  Artikelnummer                 Artikel Stückartikel  Anzahl_Kellen  \
0  463705       91862294         Kartoffelpüree             N              2
1  463705       91533770                Wirsing             N              1
2  463705       91562770            Rinderbraten            J              1
3  463705       93858626  Dunkle Balsamico-Sauce            N              1
4  463706       91862294         Kartoffelpüree             N              2

  Gewicht_Kelle Gewicht_Teller kcal_Teller kj_Teller Fett_Teller  \
0          60,0          120,0     129,960   544,440       5,640
1          80,0           80,0      33,600   138,400       0,400
2          90,0           90,0     116,100   485,100       4,770
3          50,0           50,0      22,500    95,000       0,350
4          60,0          120,0     129,960   544,440       5,640

  ges_Fettsäuren_Teller Kohlenhydrate_Teller Zucker_Teller Eiweiß_Teller  \
0                 0,600               16,440         0,480         2,040
1                 0,080                4,560         3,680         1,600
2                 1,980                0,000         0,000        18,180
3                 0,050                4,300         2,800         0,350
4                 0,600               16,440         0,480         2,040

  Salz_Teller
0       0,960
1       0,800
2       0,810
3       0,300
4       0,960
Loaded CSV file: ../csv/Mengen Rückläufer (CSV) - 1&2.csv
   Bon_ID   Artikelnr Menge_Rückläufer Prozent_Rückläufer
0  455041  91511793.0            95,00             100,00
1  455041  91366742.0            66,00             100,00
2  455041  93709884.0            52,00              52,00
3  455041         NaN            53,30             100,00
4  455046         NaN           210,00              44,12
Number of images loaded: 219

In [2]:
csv_data[0]

,Bon_ID,Gericht,Portionsgröße,Gewicht_vorher,kcal_vorher,kj_vorher,Fett_vorher,ges_Fettsäuren_vorher,Kohlenhydrate_vorher,Zucker_vorher,...,Salz_vorher,Gewicht_nachher,kcal_nachher,kj_nachher,Fett_nachher,ges_fettsäuren_nachher,Kohlenhydrate_nachher,Zucker_nachher,Eiweiß_nachher,Salz_nachher
0,463705,"Rinderbraten mit Wirsing , Kartoffelpüree , Du...",Normale Portion,340,"302,160","1.262,940","11,160","2,710","25,300","6,960",...,"2,870",630,"281,484","1.176,556","10,354","2,556","23,314","6,636","21,038","2,678"
1,463706,"Rinderbraten mit Wirsing , Kartoffelpüree , Du...",Normale Portion,340,"302,160","1.262,940","11,160","2,710","25,300","6,960",...,"2,870",298,"261,078","1.091,247","9,593","2,244","22,871","6,292","18,151","2,510"
2,463707,"Schweinenackenbraten mit Rotkohl , Kartoffeln ...",Normale Portion,295,"299,850","1.254,800","14,000","5,120","23,265","8,625",...,"2,530",247,"215,690","902,420","8,410","3,026","21,711","7,923","11,617","2,092"
3,463711,"Schweinenackenbraten , Rotkohl , Kartoffeln , ...",Normale Portion,295,"299,850","1.254,800","14,000","5,120","23,265","8,625",...,"2,530",203,"190,930","799,500","8,398","3,014","16,695","6,887","10,981","1,692"
4,463712,Pasta mit Pilzen und Gemüse an Tomatensauce,Normale Portion,340,"341,500","1.433,300","7,630","1,070","53,190","9,240",...,"1,650",266,"267,174","1.121,346","5,969","0,837","41,613","7,229","9,435","1,291"
5,463715,Pasta mit Pilzen und Gemüse an Tomatensauce,Normale Portion,340,"341,500","1.433,300","7,630","1,070","53,190","9,240",...,"1,650",310,"311,368","1.306,832","6,957","0,976","48,497","8,425","10,996","1,504"
6,463719,"Rinderbraten mit Wirsing , Kartoffelpüree , Du...",Normale Portion,340,"302,160","1.262,940","11,160","2,710","25,300","6,960",...,"2,870",284,"248,892","1.040,628","9,152","2,128","22,082","6,068","17,094","2,364"
7,463721,"Schweinenackenbraten mit Rotkohl , Kartoffeln ...",Normale Portion,295,"299,850","1.254,800","14,000","5,120","23,265","8,625",...,"2,530",245,"238,790","999,440","10,756","3,900","19,887","7,585","14,191","2,068"

In [3]:
csv_data[1]

,Bon_ID,Artikelnummer,Artikel,Stückartikel,Anzahl_Kellen,Gewicht_Kelle,Gewicht_Teller,kcal_Teller,kj_Teller,Fett_Teller,ges_Fettsäuren_Teller,Kohlenhydrate_Teller,Zucker_Teller,Eiweiß_Teller,Salz_Teller
0,463705,91862294,Kartoffelpüree,N,2,"60,0","120,0","129,960","544,440","5,640","0,600","16,440","0,480","2,040","0,960"
1,463705,91533770,Wirsing,N,1,"80,0","80,0","33,600","138,400","0,400","0,080","4,560","3,680","1,600","0,800"
2,463705,91562770,Rinderbraten,J,1,"90,0","90,0","116,100","485,100","4,770","1,980","0,000","0,000","18,180","0,810"
3,463705,93858626,Dunkle Balsamico-Sauce,N,1,"50,0","50,0","22,500","95,000","0,350","0,050","4,300","2,800","0,350","0,300"
4,463706,91862294,Kartoffelpüree,N,2,"60,0","120,0","129,960","544,440","5,640","0,600","16,440","0,480","2,040","0,960"
5,463706,91533770,Wirsing,N,1,"80,0","80,0","33,600","138,400","0,400","0,080","4,560","3,680","1,600","0,800"
6,463706,91562770,Rinderbraten,J,1,"90,0","90,0","116,100","485,100","4,770","1,980","0,000","0,000","18,180","0,810"
7,463706,93858626,Dunkle Balsamico-Sauce,N,1,"50,0","50,0","22,500","95,000","0,350","0,050","4,300","2,800","0,350","0,300"
8,463707,91511793,Kartoffeln,N,1,"95,0","95,0","56,050","231,800","0,000","0,000","11,685","0,475","1,425","0,760"
9,463707,91366696,Rotkohl,N,1,"50,0","50,0","24,500","103,500","0,050","0,050","4,500","3,650","0,650","0,600"
10,463707,91562779,Schweinenackenbraten,J,1,"90,0","90,0","186,300","780,300","13,230","4,950","1,080","0,900","15,930","0,810"
11,463707,93858715,Malzbier-Senf-Sauce,N,1,"60,0","60,0","33,000","139,200","0,720","0,120","6,000","3,600","0,480","0,360"
12,463711,91511793,Kartoffeln,N,1,"95,0","95,0","56,050","231,800","0,000","0,000","11,685","0,475","1,425","0,760"
13,463711,91366696,Rotkohl,N,1,"50,0","50,0","24,500","103,500","0,050","0,050","4,500","3,650","0,650","0,600"
14,463711,91562779,Schweinenackenbraten,J,1,"90,0","90,0","186,300","780,300","13,230","4,950","1,080","0,900","15,930","0,810"
15,463711,93858715,Malzbier-Senf-Sauce,N,1,"60,0","60,0","33,000","139,200","0,720","0,120","6,000","3,600","0,480","0,360"
16,463712,91389092,Nudeln,N,2,"65,0","130,0","228,800","963,300","3,120","0,520","40,430","0,780","8,320","0,000"
17,463712,91511769,Möhre,N,2,"40,0","80,0","37,600","157,600","2,000","0,160","4,480","4,320","0,480","0,560"
18,463712,91388363,Pilze,N,1,"30,0","30,0","6,300","25,200","0,150","0,030","0,480","0,060","0,540","0,150"
19,463712,91511750,Erbsen,N,1,"40,0","40,0","36,400","151,600","1,160","0,120","3,480","1,200","2,000","0,040"
20,463712,91412663,Tomatensauce,N,1,"60,0","60,0","32,400","135,600","1,200","0,240","4,320","2,880","0,720","0,900"
21,463715,91389092,Nudeln,N,2,"65,0","130,0","228,800","963,300","3,120","0,520","40,430","0,780","8,320","0,000"
22,463715,91511769,Möhre,N,2,"40,0","80,0","37,600","157,600","2,000","0,160","4,480","4,320","0,480","0,560"
23,463715,91388363,Pilze,N,1,"30,0","30,0","6,300","25,200","0,150","0,030","0,480","0,060","0,540","0,150"
24,463715,91511750,Erbsen,N,1,"40,0","40,0","36,400","151,600","1,160","0,120","3,480","1,200","2,000","0,040"
25,463715,91412663,Tomatensauce,N,1,"60,0","60,0","32,400","135,600","1,200","0,240","4,320","2,880","0,720","0,900"
26,463719,91862294,Kartoffelpüree,N,2,"60,0","120,0","129,960","544,440","5,640","0,600","16,440","0,480","2,040","0,960"
27,463719,91533770,Wirsing,N,1,"80,0","80,0","33,600","138,400","0,400","0,080","4,560","3,680","1,600","0,800"
28,463719,91562770,Rinderbraten,J,1,"90,0","90,0","116,100","485,100","4,770","1,980","0,000","0,000","18,180","0,810"
29,463719,93858626,Dunkle Balsamico-Sauce,N,1,"50,0","50,0","22,500","95,000","0,350","0,050","4,300","2,800","0,350","0,300"
30,463721,91511793,Kartoffeln,N,1,"95,0","95,0","56,050","231,800","0,000","0,000","11,685","0,475","1,425","0,760"
31,463721,91366696,Rotkohl,N,1,"50,0","50,0","24,500","103,500","0,050","0,050","4,500","3,650","0,650","0,600"
32,463721,91562779,Schweinenackenbraten,J,1,"90,0","90,0","186,300","780,300","13,230","4,950","1,080","0,900","15,930","0,810"
33,463721,93858715,Malzbier-Senf-Sauce,N,1,"60,0","60,0","33,000","139,200","0,720","0,120","6,000","3,600","0,480","0,360"

In [4]:
csv_data[2]

    Bon_ID   Artikelnr Menge_Rückläufer Prozent_Rückläufer
0   455041  91511793.0            95,00             100,00
1   455041  91366742.0            66,00             100,00
2   455041  93709884.0            52,00              52,00
3   455041         NaN            53,30             100,00
4   455046         NaN           210,00              44,12
5   455048  91366696.0            10,00              10,00
6   455048  91562770.0            18,00              20,00
7   455049         NaN           222,00              47,23
8   455054  91560638.0            68,00              56,67
9   455054  91366696.0            80,00              80,00
10  455054  91562770.0            56,00              62,22
11  455054         NaN            50,00             100,00
12  463705  91862294.0            12,00              10,00
13  463705  91533770.0             6,00               7,50
14  463705  91562770.0             4,00               4,44
15  463705         NaN          -312,00            -624,00
16  463706  91562770.0            18,00              20,00
17  463706         NaN            24,00               9,60
18  463707  91511793.0             6,00               6,32
19  463707  91366696.0             4,00               8,00
20  463707  91562779.0            38,00              42,22
21  463711  91511793.0            38,00              40,00
22  463711  91366696.0            16,00              32,00
23  463711  91562779.0            38,00              42,22
24  463712         NaN            74,00              21,77
25  463715         NaN            30,00               8,82
26  463719  91862294.0            16,00              13,33
27  463719  91533770.0            18,00              22,50
28  463719  91562770.0            22,00              24,44
29  463721  91511793.0            18,00              18,95
30  463721  91366696.0            10,00              20,00
31  463721  91562779.0            22,00              24,44

In [5]:
df1 = csv_data[1]
df2 = csv_data[2]
# df3 = df1.merge(df2, how='left', left_on=['Bon_ID', 'Artikelnummer'], right_on=['Bon_ID', 'Artikelnr'])
df3 = df1.copy()

# Convert Menge_Rückläufer and Prozent_Rückläufer to float
df2['Menge_Rückläufer'] = df2['Menge_Rückläufer'].apply(lambda x: float(str(x).replace(',', '.')))
df2['Prozent_Rückläufer'] = df2['Prozent_Rückläufer'].apply(lambda x: float(str(x).replace(',', '.')))

# Add the new columns to df3
df3['Menge_Rückläufer'] = 0
df3['Prozent_Rückläufer'] = 0
df3['Menge_Rückläufer'] = df3['Menge_Rückläufer'].astype(float)
df3['Prozent_Rückläufer'] = df3['Prozent_Rückläufer'].astype(float)
# First, add the values for non-NaN Artikelnr
for _, row in df2.iterrows():
    bon_id = int(row['Bon_ID'])
    artikelnr = row['Artikelnr']
    menge_ruecklaeufer = row['Menge_Rückläufer']
    prozent_ruecklaeufer = row['Prozent_Rückläufer']
    
    if pd.notna(artikelnr):
        # If Artikelnr is not NaN, add the values to the corresponding rows in df1
        df3.loc[(df3['Bon_ID'] == bon_id) & (df3['Artikelnummer'] == artikelnr), 'Menge_Rückläufer'] += menge_ruecklaeufer
        df3.loc[(df3['Bon_ID'] == bon_id) & (df3['Artikelnummer'] == artikelnr), 'Prozent_Rückläufer'] += prozent_ruecklaeufer

# Then, distribute the values for NaN Artikelnr
for _, row in df2.iterrows():
    bon_id = int(row['Bon_ID'])
    artikelnr = row['Artikelnr']
    menge_ruecklaeufer = row['Menge_Rückläufer']
    prozent_ruecklaeufer = row['Prozent_Rückläufer']
    
    if pd.isna(artikelnr):
        # If Artikelnr is NaN, distribute the values among the rest of the Artikelnr found in the Bon_ID
        df1_subset = df3[(df3['Bon_ID'] == bon_id) & (df3['Menge_Rückläufer'] == 0) & (df3['Prozent_Rückläufer'] == 0)]
        num_existing_artikelnr = len(df1_subset)
        if num_existing_artikelnr > 0:
            df3.loc[(df3['Bon_ID'] == bon_id) & (df3['Menge_Rückläufer'] == 0), 'Menge_Rückläufer'] += menge_ruecklaeufer / num_existing_artikelnr
            df3.loc[(df3['Bon_ID'] == bon_id) & (df3['Prozent_Rückläufer'] == 0), 'Prozent_Rückläufer'] += prozent_ruecklaeufer / num_existing_artikelnr

# Display the updated DataFrame
print(df3.head())

   Bon_ID  Artikelnummer                 Artikel Stückartikel  Anzahl_Kellen  \
0  463705       91862294         Kartoffelpüree             N              2
1  463705       91533770                Wirsing             N              1
2  463705       91562770            Rinderbraten            J              1
3  463705       93858626  Dunkle Balsamico-Sauce            N              1
4  463706       91862294         Kartoffelpüree             N              2

  Gewicht_Kelle Gewicht_Teller kcal_Teller kj_Teller Fett_Teller  \
0          60,0          120,0     129,960   544,440       5,640
1          80,0           80,0      33,600   138,400       0,400
2          90,0           90,0     116,100   485,100       4,770
3          50,0           50,0      22,500    95,000       0,350
4          60,0          120,0     129,960   544,440       5,640

  ges_Fettsäuren_Teller Kohlenhydrate_Teller Zucker_Teller Eiweiß_Teller  \
0                 0,600               16,440         0,480         2,040
1                 0,080                4,560         3,680         1,600
2                 1,980                0,000         0,000        18,180
3                 0,050                4,300         2,800         0,350
4                 0,600               16,440         0,480         2,040

  Salz_Teller  Menge_Rückläufer  Prozent_Rückläufer
0       0,960              12.0               10.00
1       0,800               6.0                7.50
2       0,810               4.0                4.44
3       0,300            -312.0             -624.00
4       0,960               8.0                3.20

In [11]:
df3.drop(df3[df3['Bon_ID'] == 463705].index, inplace=True)

In [12]:
df3.to_csv('merged_data.csv', index=False)

In [13]:
df3

,Bon_ID,Artikelnummer,Artikel,Stückartikel,Anzahl_Kellen,Gewicht_Kelle,Gewicht_Teller,kcal_Teller,kj_Teller,Fett_Teller,ges_Fettsäuren_Teller,Kohlenhydrate_Teller,Zucker_Teller,Eiweiß_Teller,Salz_Teller,Menge_Rückläufer,Prozent_Rückläufer
4,463706,91862294,Kartoffelpüree,N,2,"60,0","120,0","129,960","544,440","5,640","0,600","16,440","0,480","2,040","0,960",8.0,3.200
5,463706,91533770,Wirsing,N,1,"80,0","80,0","33,600","138,400","0,400","0,080","4,560","3,680","1,600","0,800",8.0,3.200
6,463706,91562770,Rinderbraten,J,1,"90,0","90,0","116,100","485,100","4,770","1,980","0,000","0,000","18,180","0,810",18.0,20.000
7,463706,93858626,Dunkle Balsamico-Sauce,N,1,"50,0","50,0","22,500","95,000","0,350","0,050","4,300","2,800","0,350","0,300",8.0,3.200
8,463707,91511793,Kartoffeln,N,1,"95,0","95,0","56,050","231,800","0,000","0,000","11,685","0,475","1,425","0,760",6.0,6.320
9,463707,91366696,Rotkohl,N,1,"50,0","50,0","24,500","103,500","0,050","0,050","4,500","3,650","0,650","0,600",4.0,8.000
10,463707,91562779,Schweinenackenbraten,J,1,"90,0","90,0","186,300","780,300","13,230","4,950","1,080","0,900","15,930","0,810",38.0,42.220
11,463707,93858715,Malzbier-Senf-Sauce,N,1,"60,0","60,0","33,000","139,200","0,720","0,120","6,000","3,600","0,480","0,360",0.0,0.000
12,463711,91511793,Kartoffeln,N,1,"95,0","95,0","56,050","231,800","0,000","0,000","11,685","0,475","1,425","0,760",38.0,40.000
13,463711,91366696,Rotkohl,N,1,"50,0","50,0","24,500","103,500","0,050","0,050","4,500","3,650","0,650","0,600",16.0,32.000
14,463711,91562779,Schweinenackenbraten,J,1,"90,0","90,0","186,300","780,300","13,230","4,950","1,080","0,900","15,930","0,810",38.0,42.220
15,463711,93858715,Malzbier-Senf-Sauce,N,1,"60,0","60,0","33,000","139,200","0,720","0,120","6,000","3,600","0,480","0,360",0.0,0.000
16,463712,91389092,Nudeln,N,2,"65,0","130,0","228,800","963,300","3,120","0,520","40,430","0,780","8,320","0,000",14.8,4.354
17,463712,91511769,Möhre,N,2,"40,0","80,0","37,600","157,600","2,000","0,160","4,480","4,320","0,480","0,560",14.8,4.354
18,463712,91388363,Pilze,N,1,"30,0","30,0","6,300","25,200","0,150","0,030","0,480","0,060","0,540","0,150",14.8,4.354
19,463712,91511750,Erbsen,N,1,"40,0","40,0","36,400","151,600","1,160","0,120","3,480","1,200","2,000","0,040",14.8,4.354
20,463712,91412663,Tomatensauce,N,1,"60,0","60,0","32,400","135,600","1,200","0,240","4,320","2,880","0,720","0,900",14.8,4.354
21,463715,91389092,Nudeln,N,2,"65,0","130,0","228,800","963,300","3,120","0,520","40,430","0,780","8,320","0,000",6.0,1.764
22,463715,91511769,Möhre,N,2,"40,0","80,0","37,600","157,600","2,000","0,160","4,480","4,320","0,480","0,560",6.0,1.764
23,463715,91388363,Pilze,N,1,"30,0","30,0","6,300","25,200","0,150","0,030","0,480","0,060","0,540","0,150",6.0,1.764
24,463715,91511750,Erbsen,N,1,"40,0","40,0","36,400","151,600","1,160","0,120","3,480","1,200","2,000","0,040",6.0,1.764
25,463715,91412663,Tomatensauce,N,1,"60,0","60,0","32,400","135,600","1,200","0,240","4,320","2,880","0,720","0,900",6.0,1.764
26,463719,91862294,Kartoffelpüree,N,2,"60,0","120,0","129,960","544,440","5,640","0,600","16,440","0,480","2,040","0,960",16.0,13.330
27,463719,91533770,Wirsing,N,1,"80,0","80,0","33,600","138,400","0,400","0,080","4,560","3,680","1,600","0,800",18.0,22.500
28,463719,91562770,Rinderbraten,J,1,"90,0","90,0","116,100","485,100","4,770","1,980","0,000","0,000","18,180","0,810",22.0,24.440
29,463719,93858626,Dunkle Balsamico-Sauce,N,1,"50,0","50,0","22,500","95,000","0,350","0,050","4,300","2,800","0,350","0,300",0.0,0.000
30,463721,91511793,Kartoffeln,N,1,"95,0","95,0","56,050","231,800","0,000","0,000","11,685","0,475","1,425","0,760",18.0,18.950
31,463721,91366696,Rotkohl,N,1,"50,0","50,0","24,500","103,500","0,050","0,050","4,500","3,650","0,650","0,600",10.0,20.000
32,463721,91562779,Schweinenackenbraten,J,1,"90,0","90,0","186,300","780,300","13,230","4,950","1,080","0,900","15,930","0,810",22.0,24.440
33,463721,93858715,Malzbier-Senf-Sauce,N,1,"60,0","60,0","33,000","139,200","0,720","0,120","6,000","3,600","0,480","0,360",0.0,0.000